In [9]:
%reset -f

from pathlib import Path
import pandas as pd
# import nrarfcn as nr
import duckdb

In [8]:
repo = Path.cwd()
print(repo)

dfLteRadioNeig = pd.read_csv(f'{repo}/data/_csvs/Nyc2026Apr/20260612/lte_radio_neig.csv')
dfLteRadio = pd.read_csv(f'{repo}/data/_csvs/Nyc2026Apr/20260612/lte_radio.csv')
dfLtePdsch = pd.read_csv(f'{repo}/data/_csvs/Nyc2026Apr/20260612/lte_pdsch.csv')
dfLtePusch = pd.read_csv(f'{repo}/data/_csvs/Nyc2026Apr/20260612/lte_pusch.csv')

dfNrRadioNeig = pd.read_csv(f'{repo}/data/_csvs/Nyc2026Apr/20260612/nr_radio_neig.csv')
dfNrRadio = pd.read_csv(f'{repo}/data/_csvs/Nyc2026Apr/20260612/nr_radio.csv')
dfNrPdsch = pd.read_csv(f'{repo}/data/_csvs/Nyc2026Apr/20260612/nr_pdsch.csv')
dfNrPusch = pd.read_csv(f'{repo}/data/_csvs/Nyc2026Apr/20260612/nr_pusch.csv')

/home/jpalathi/Documents/Repos/_research/cellular-website

In [ ]:
repo = Path.cwd()
con = duckdb.connect(repo / "data/_processed/cellular.duckdb", read_only=True)

con.sql("SHOW TABLES").df()

                     name
0             collections
1  measurement_partitions
2         processed_files

In [15]:
con.sql("SELECT * FROM collections").df()

,database_name,collection_name,start_time,end_time,latest_export_date,has_lte,has_nr
0,Nyc2026Apr,20260403_OrdIndoor_b8FacingWindow,2026-04-03 05:52:09.500,2026-04-03 05:59:35.942,2026-06-12,True,True
1,Nyc2026Apr,20260404_NycIndoor,2026-04-04 18:28:07.773,2026-04-04 18:42:55.641,2026-06-12,True,True
2,Nyc2026Apr,20260405_NycIndoor_NearWindow,2026-04-05 12:50:29.356,2026-04-05 13:31:08.580,2026-06-12,True,True
3,Nyc2026Apr,20260404_NycOutdoor_Walking,2026-04-04 11:23:22.349,2026-04-04 19:40:32.487,2026-06-12,True,True
4,Nyc2026Apr,20260403_NycOutdoor_Driving,2026-04-03 09:50:13.771,2026-04-03 10:06:21.406,2026-06-12,True,True
5,Nyc2026Apr,20260403_OrdIndoor_b8FacingTerminal,2026-04-03 06:01:08.776,2026-04-03 06:08:25.302,2026-06-12,True,True